2024-03-05 20:17:38,133 ERROR: Exception on /add-tool [POST] [in /data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/tool/views.py", line 35, in addTool
    tool = Tool(
           ^^^^^
  File "<string>", line 4, in __init__
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 566, in _initialize_instance
    with util.safe_reraise():
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 2142, in _declarative_constructor
    raise TypeError(
TypeError: 'author' is an invalid keyword argument for Tool
2024-03-05 20:21:14,440 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-05 20:21:40,238 ERROR: Exception on /get-tools [GET] [in /data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/tool/views.py", line 16, in getTools
    return jsonify({'tools': render_template('tool/get_tools.html', title = 'Ferramentas', tools = tools.items, prev_url = prev_url, next_url = next_url)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/templates/tool/get_tools.html", line 16, in top-level template code
    <td>{{ tool.author.name }}</td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.models.Tool object' has no attribute 'author'
2024-03-05 20:23:44,296 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-05 20:23:50,139 ERROR: Exception on /view-tool [GET] [in /data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/tool/views.py", line 61, in viewTool
    return jsonify({'view_tool_response': render_template('tool/view_tool.html', tool = tool)})
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/templates/tool/view_tool.html", line 28, in top-level template code
    {% if tool.author.github %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.models.Tool object' has no attribute 'author'
2024-03-05 20:25:56,512 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-05 20:26:07,109 ERROR: Exception on /get-data-tool [GET] [in /data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/tool/views.py", line 75, in getDataTool
    'author': tool.author.name,
              ^^^^^^^^^^^
AttributeError: 'Tool' object has no attribute 'author'
2024-03-05 20:26:40,773 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-05 20:29:27,574 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-05 20:31:24,963 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-05 20:33:44,861 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:30:32,178 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
